spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/toy_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: test
      password: 123
      roles: ADMIN

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

logging.level:
  com.github.toy : debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace